In [7]:
import pandas as pd
df = pd.read_csv("Advertising.csv")
df = df.iloc[:, 1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [14]:
X = df.drop("sales", axis=1)
y = df[["sales"]]

In [15]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [16]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [17]:
# Create model with statsmodel
import statsmodels.api as sm
lm = sm.OLS(y, X)
model = lm.fit()

In [18]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sat, 10 Aug 2024   Prob (F-statistic):                   2.43e-171
Time:                        22:13:07   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [19]:
# Create model with sklearn
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [20]:
model = lm.fit(X, y)

In [21]:
model.intercept_

array([2.93888937])

In [22]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

In [24]:
2.94 + 30 * 0.04 + 10 * 0.19 - 40 * 0.001

5.999999999999999

In [25]:
new_data = [[30], [10], [40]]

In [26]:
new_data = pd.DataFrame(new_data).T

In [27]:
new_data

0   1   2
0  30  10  40

In [29]:
model.predict(new_data)

c:\Users\SAMSUNG\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [30]:
from sklearn.metrics import mean_squared_error
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [31]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [34]:
import numpy as np

In [35]:
# Find mean squared error
mse = mean_squared_error(y, model.predict(X))
mse

2.784126314510936

In [36]:
# Find root mean squared error
rmse = np.sqrt(mse)
rmse

1.6685701407225697